### ISSUE TITLE
optimize ProcessListVRS to reuse existing Hours if possible

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#154]
When ProcessListJRS calls ProcessListVRS, we delete all Hours that aren't completed or canceled, and then recreate them.  Since this happens every time the scheduled job runs, it would be better to reuse existing hours if they still meet the VRS schedule.  Not a trivial code change, however.

**Comment by davidhabib** [comment]
In release 3.79, I added code to remove the deleted Hours from the Recycle Bin.

**Comment by mpusto** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004DBJaAAO" target="_blank">W-016882</a>

**Comment by davidhabib** [comment]
Another reason to do this optimization is to preserve additional Hours Status changes that the user may have made.  For example, if the VRS has a status of Confirmed, but later the user has updated some past Hours to Status=No-Show, we don't want ProcessListJRS to have a side effect of deleting the No-Show Hours, and recreating them with Confirmed.

Also note that ProcessListVRS will look at ALL shifts for the Job, rather than just new shifts added due to a new or updated JRS.  So adding a new JRS has a side effect of deleting/recreating Hours that have nothing to do with the new JRS added.

**Comment by davidhabib** [comment]
While investigating this issue, also review where we look at Status, to see if we can do more to support custom Status values.

**Comment by jlantz** [comment]
Included in beta release 3.90 (Beta 3)
