### ISSUE TITLE
Duplicate Rules causing issues with web signups?

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#156]
hub thread: https://powerofus.force.com/0D58000002I4t9b

**Comment by davidhabib** [comment]
might need to change V4S code to specify updates should succeed.  Here's a snippet from NPSP Lead Convert that changed for this:
https://github.com/SalesforceFoundation/Cumulus/commit/78c9c4988124c6bfe555a8237c5eb0d1672f91fb

Database.DMLOptions dml = new Database.DMLOptions();
-            	CON_ContactMerge.mergeContacts((Contact)master, losers);		+                dml.DuplicateRuleHeader.AllowSave = true;
+                Database.SaveResult sr = Database.update(master, dml);

**Comment by mpusto** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004AWvdAAG" target="_blank">W-016763</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.91 (Beta 6)
