### ISSUE TITLE
on VolunteersJobListingFS popup, prevent user from clicking "Sign Up" multiple times

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#184]
hub thread: https://powerofus.force.com/0D58000002asO7w

**Comment by mpusto** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004DBJUAA4" target="_blank">W-016877</a>

**Comment by jessingrass** [comment]
After testing, it appears that the sign-up button in /VolunteersJobListingFS pop-up modal can be clicked multiple times without an indication that the initial click has caused an underlying action to occur. Therefore, user may click sign-up multiple times before the modal closes, thus creating multiple sign-ups. Please find attached screenshots of the modal and the results.

Repro:
1. fill in required info
2. click sign-up as many times as you want or can until modal says thank you
3. check volunteer job and see that sign-up is as many clicks as you made

![screen shot 2016-12-15 at 9 41 24 pm](https://cloud.githubusercontent.com/assets/1976801/21250061/461b3eb8-c310-11e6-903e-af53debb0f6c.png)
![screen shot 2016-12-15 at 9 49 03 pm](https://cloud.githubusercontent.com/assets/1976801/21250066/55a0d1a4-c310-11e6-90bf-6475419cabd4.png)

**Comment by mrbelvedere** [comment]
Included in beta release 3.91 (Beta 5)
