### ISSUE TITLE
provide more control over JobCalendar shift colors

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#190]
hub thread: https://powerofus.force.com/0D58000002ggTeq

**Comment by mpusto** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004DBJRAA4" target="_blank">W-016874</a>

**Comment by davidhabib** [comment]
duplicate of #296
