### ISSUE TITLE
Mass Email Volunteer: View Templates & Edit Templates don't work under Lightning Experience

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#192]
those links point to pages under setup, which only work under Classic, not LEX.

**Comment by GeorgeGre** [comment]
In Enterprise, when clicking Mass Email Volunteers, the following error is thrown:
"The link you followed wasn’t valid for your session. Return to the previous page, refresh it, and try again."
This started after Friday, June 3 (last known working date).

Is this a related defect? The instruction to refresh doesn't work.

**Comment by davidhabib** [comment]
the Mass Email Volunteers is a known issue. see this hub post: https://powerofus.force.com/0D58000002kgTUE

**Comment by GeorgeGre** [comment]
Thank you! It was a showstopper until now.
George Greiner
Database Administrator
Jacob’s Pillow Dance Festival
www.jacobspillow.org<http://www.jacobspillow.org>

**Comment by mpusto** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004DBJPAA4" target="_blank">W-016872</a>
