### ISSUE TITLE
better support for State & Country Picklists

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#200]
hub thread: https://powerofus.force.com/0D58000002pe7bd

**Comment by mpusto** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004AWvXAAW" target="_blank">W-016760</a>

**Comment by jlantz** [comment]
Included in beta release 3.90 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.90
