### ISSUE TITLE
Lightning Experience: Volunteer Roster button/action not filtering report

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#206]
Under LEX, the report comes up, but displays no data, because the filtering does not get updated to the campaign, job, or shift it was invoked from.

**Comment by mpusto** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004poxzAAA" target="_blank">W-017645</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.94 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.94
