### ISSUE TITLE
Lightning Experience: update styling of all visuaforce pages to use SLDS

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#207]
all of the internal custom visualforce pages in V4S need to get restyled to use SLDS.  This includes:
- Mass Email Volunteers
- Mass Edit Hours
- Job Calendar
- New & Edit VRS override page
- Volunteers Wizard
- Find Volunteers

this work does NOT include doing anything to the Sites pages, as those appear outside of Salesforce, and already support styling by the customer using an included CSS file.

**Comment by mpusto** [comment]
@davidhabib can we close this as we broke it into separate stories and addressed those pages individually?
