### ISSUE TITLE
improve UX for selection of dependent picklists in Mass Enter Volunteer Hours page

### ISSUE THREAD

**Issue by mpusto** [SalesforceFoundation/Volunteers-for-Salesforce#219]
See comment thread [here](https://github.com/SalesforceFoundation/Volunteers-for-Salesforce/pull/213#issuecomment-259741880) for details on the issue in question. Have engaged UX for further clarification on recommended best practices.

**Comment by mpusto** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004Br2uAAC" target="_blank">W-016858</a>
