### ISSUE TITLE
Mass Email Volunteers no longer display number of contacts

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#224]
when we applied SLDS to the Mass Email Volunteers page, we broke the rerendering on the Number of Contact Emails field.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004FvbeAAC" target="_blank">W-017080</a>

**Comment by jlantz** [comment]
Included in beta release 3.89 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.89
