### ISSUE TITLE
V4S: New Volunteer Recurrence page cannot be canceled always

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#228]
if any of the required fields are not filled in, you are unable to cancel the page, due to getting required field errors.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004Ii5jAAC" target="_blank">W-017209</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.90 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.90
