### ISSUE TITLE
V4S: Contact with multiple VRS's to same Job no longer work

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#230]
hub thread: https://powerofus.force.com/0D580000037OeYM

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004Ii63AAC" target="_blank">W-017213</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.90 (Beta 10)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.90
