### ISSUE TITLE
Sign Up popup for Volunteer Jobs Listing is poorly positioned on tall pages

### ISSUE THREAD

**Issue by dylanmccall** [SalesforceFoundation/Volunteers-for-Salesforce#24]
Steps to reproduce:
- Insert a Volunteer Jobs Listing inside an iframe with a particularly large height. (3600px, for example).
- Click the Sign Up button for any job in the list.
- The Sign Up popup will appear halfway down the page, far away from any content — especially the selected volunteer opportunity.

You can see this in action over here: http://www.davidsuzuki.org/about/volunteer/current-volunteer-opportunities/

If we set the iframe height to something like 1000px, the popup appears in a more normal looking place, but that means we have to put up with an extra scrollbar.

The popup's position should not be related to page height, because that is unreliable with an iframe. Instead, its position should be related to the selected volunteer opportunity.

**Comment by davidhabib** [comment]
Unfortunately, in V4S 3.99 we updated to the latest JQueryUI library (per security review requirements), which broke the positioning functionality in Firefox.  We've had to remove the positioning fix for now to go back to JQueryUI's default dialog positioning, which is the center of the page.  This means on long pages, we are ugly again, so I'm reopening this issue, so we come up with a fix that works with latest JQueryUI and across all browsers!

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000001SDJAAA4" target="_blank">W-020957</a>

**Comment by cpolcyn** [comment]
Closed by https://github.com/SalesforceFoundation/Volunteers-for-Salesforce/pull/318

**Comment by mrbelvedere** [comment]
Included in beta release 3.101 (Beta 4)

**Comment by cpolcyn** [comment]
Included in production release rel/3.101
