### ISSUE TITLE
Job Calendar translations for German and Japanese are incorrect

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#244]
Some of the custom labels used by the JobCalendar page are not in the correct format when they were translated for German and Japanese.  Specifically, labelColorValues should not get translated and just contain english color names.  labelCalendarButtonText has the tags that need to be in english translated.  One can see how French and Spanish are done to get it fixed.  There might be other custom labels incorrectly translated for German and Japanese; we obviously have not done any testing. :-(

Hub post: https://powerofus.force.com/0D580000039cCVu

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004RBbMAAW" target="_blank">W-017397</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.93 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.93
