### ISSUE TITLE
geolocation fields give error in Personal Sites

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#246]
if you have any geolocation fields on contact, and you are using PersonalSites, you will receive errors trying to view the JobListingFS or ReportHours pages from the PersonalSite.  The is due to V4S code calling VOL_SharedCodeAPI25.LoadAndCopyObject(), which gives an error:

EXCEPTION_THROWN [58]|System.QueryException: No such column 'mygeofield__c' on entity 'Contact'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.

The soql the code generated was:

SOQL_EXECUTE_BEGIN [58]|Aggregations:0|select id, isdeleted, masterrecordid, accountid, lastname, firstname, salutation, name, otherstreet, othercity, otherstate, otherpostalcode, othercountry, mailingstreet, mailingcity, mailingstate, mailingpostalcode, mailingcountry, phone, fax, mobilephone, homephone, otherphone, assistantphone, reportstoid, email, title, department, assistantname, leadsource, birthdate, description, ownerid, hasoptedoutofemail, hasoptedoutoffax, donotcall, createddate, createdbyid, lastmodifieddate, lastmodifiedbyid, systemmodstamp, lastactivitydate, lastcurequestdate, lastcuupdatedate, lastvieweddate, emailbouncedreason, emailbounceddate, jigsaw, jigsawcontactid, level__c, languages__c, unique_volunteer_count__c, volunteer_auto_reminder_email_opt_out__c, volunteer_availability__c, volunteer_last_web_signup_date__c, volunteer_manager_notes__c, volunteer_notes__c, volunteer_organization__c, volunteer_skills__c, volunteer_status__c, first_volunteer_date__c, last_volunteer_date__c, volunteer_hours__c, mygeofield__latitude__s, mygeofield__longitude__s, mygeofield__c from Contact where Id = :id  limit 1

The code explicitly avoids this problem with the compound address fields by removing mailingaddress and compoundaddress from the set of fields.  

Unfortunately, not sure how the code can detect that it is seeing a compound field to exclude it from the soql.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by davidhabib** [comment]
hub thread: https://powerofus.force.com/0D58000003AWUNz

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004bGgdAAE" target="_blank">W-017457</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.92 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.92
