### ISSUE TITLE
Calender not loading 

### ISSUE THREAD

**Issue by webistan** [SalesforceFoundation/Volunteers-for-Salesforce#248]
On Volunteer personal info (PersonalSiteContactinfo) Calendar is not loading. 

I searched over the community and people asking to use lower API version i.e 29 but its still not working. 

can you help me how to fix it?

**Comment by davidhabib** [comment]
You need to post questions like these on the Power of Us Hub in the Volunteers for Salesforce App group.  https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000Cjjx

thanks.
