### ISSUE TITLE
Job Recurrence Schedule Changes Deletes Volunteers Hours

### ISSUE THREAD

**Issue by mmotamimi** [SalesforceFoundation/Volunteers-for-Salesforce#249]
When my client change the end date of a volunteer recurrence schedule, all of the related volunteer hours are being deleted and recreated according to the new end date.
That is a problem to my client since the volunteer hours are being filled with data, and all of the data in the volunteers hours is lost once deleted.
I think that you should deleted only the volunteer hours that is to come yet.

**Comment by davidhabib** [comment]
Here is how VRS's and JRS's work.  If you find it diverges from this, then let us know.  But I suspect you will find that what you are asking for does not match our spec.

Recurrence Schedule Processing
How do my Shifts and Hours get processed when using Job Recurrence Schedules (JRS) and Volunteer Recurrence Schedules (VRS)?
 
When a JRS is created the system will:
Create all Shifts for the JRS, including Shifts in the past
Future Shifts will be created up to the number of months in the future specified in Volunteers Settings, in the setting Recurring Job Future Months.
Process any VRS's associated with the JRS's Job
 
When a JRS is modified the system will:
Evaluate all existing Shifts attached to the JRS
Past Shifts that no longer match the JRS, and that do not have any Hours with Status of 'Canceled' or 'Completed', will be deleted.
Future Shifts that no longer match the JRS, but have Hours with Status of 'Confirmed' or 'Completed', will be detached from the JRS and left alone.
Future Shifts that no longer match the JRS, and have no 'Confirmed' or 'Completed' Hours will be deleted.
Any existing Shifts that still match the JRS will be reused and have the following fields updated to match the JRS: Duration, Start Date & Time, Desired Number of Volunteers, and Description.
New past and future Shifts will be created that have no existing Shifts to match.
Process any VRS's associated with the JRS's Job
 
When a JRS is deleted the system will:
Delete all Shifts from the JRS who don't have Hours with Status of 'Confirmed' or 'Completed'.
 
When a VRS is created the system will:
Create Hours for the VRS, for any Shifts that match in the time range of the VRS's Start Date and optional End Date
 
When a VRS is modified the system will:
Evaluate all existing Hours attached to the VRS
Past and Future Hours that no longer match the VRS, and that do not have Status of 'Canceled' or 'Completed', will be deleted.
Past Hours that match the VRS are not modified.
Future Hours that match the VRS are reused and have the following fields updated to match the VRS: Hours Worked, Number of Volunteers, Status, Planned Start Date & Time, and Comments.
New past and future Hours will be created that have no existing Hours to match.
 
When a VRS is deleted the system will:
Delete all Hours associated with the VRS, regardless of Status.
 
When the Nightly Batch Process runs the system will:
Process each JRS, only evaluating Shifts that are in the future
Process each VRS, only evaluating Hours for those Shifts in the future
