### ISSUE TITLE
Volunteers Wizard - clone hours checkbox disabled

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#250]
In the Volunteers Wizard page, if you choose to clone from an existing Campaign, the Copy Job and Shift Volunteers checkbox is disabled and can't be checked.  we must have broken it when we SLDS'd the page.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004kdaXAAQ" target="_blank">W-017612</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.92 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.92
