### ISSUE TITLE
Custom pages with SLDS need left padding under LEX

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#252]
many of our custom v4s pages with SLDS look fine under classic, but under LEX they need some left side padding.  here's one example:

![image](https://cloud.githubusercontent.com/assets/908119/22479901/563b3790-e7a4-11e6-8431-5c44e1e1df1a.png)

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004poxkAAA" target="_blank">W-017642</a>

**Comment by davidhabib** [comment]
another example from Find Volunteers.  see how the header and footer nav links are too far left.
![image](https://cloud.githubusercontent.com/assets/908119/22479965/99d76848-e7a4-11e6-9604-b3a6446008b0.png)

**Comment by mrbelvedere** [comment]
Included in beta release 3.92 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.92
