### ISSUE TITLE
Spacing on Volunteer Wizard Page

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Volunteers-for-Salesforce#254]
Adjust the spacing of the forms top and bottom to have additional space between fields and proper alignment of read only fields on the bottom.

**Comment by jjbennett** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004poysAAA" target="_blank">W-017656</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.92 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.92
