### ISSUE TITLE
Consider changes to Scheduler's updating of future Hours?

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#256]
Sheryl Stauss (Intercongregation Communities Association Inc.) hub post here: https://powerofus.force.com/0D580000038Pp9F

When the scheduler runs and looks at future Shifts and Hours, it reuses them if they match the correct schedule, but it updates some of the fields to match the potentially modified JRS or VRS.  Specifically, I think Sheryl's hours are being updated based on this rule:

"Future Hours that match the VRS are reused and have the following fields updated to match the VRS: Hours Worked, Number of Volunteers, Status, Planned Start Date & Time, and Comments."

I think the scenario points to a valid case where the VRS should not update the Status if the Status is already set to Canceled.  But what about other fields on the VRS? when should they get updated or not touched?  Can we easily tell the difference between the user modifying the VRS, in which case you'd expect it to update most/all fields on the Hours, vs. the scheduler reverifying future hours?

@mpusto we need to go through this together to come up with any refinement we want to make to the rules as described here (internal doc): https://docs.google.com/document/d/1TwiYpVufmGie9x7nO7bNtWLw_ENP-kKU-yPP8xU3Z44/edit#

here's a copy for public viewing: 
[RecurrenceScheduleProcessing.pdf](https://github.com/SalesforceFoundation/Volunteers-for-Salesforce/files/743676/RecurrenceScheduleProcessing.pdf)

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004poyxAAA" target="_blank">W-017657</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.93 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.93
