### ISSUE TITLE
PersonalSiteContactInfo page needs to add Firstname and Lastname to soql fields

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#263]
with the improvement to only soql for fields included in field sets on the various Sites pages, we forgot to force including Firstname and Lastname for the PersonalSiteContactInfo page.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000059sz4AAA" target="_blank">W-017839</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.93 (Beta 8)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.93
