### ISSUE TITLE
pushed update from 2/21 causing VOL_Campaign_CreateStatuses trigger to fire nightly and create duplicate records from old campaigns

### ISSUE THREAD

**Issue by 4khartmann** [SalesforceFoundation/Volunteers-for-Salesforce#268]

**Comment by judisohn** [comment]
Hi @4khartmann I responded to your post on the Hub and escalated to the SFDO support team to take your case. There's something off in your instance... that trigger doesn't create Contacts. I'm going to close this and you should get a follow up from a SFDO support agent on Monday. Thanks.
