### ISSUE TITLE
Mass Edit Volunteer Hours should disable Save & Close during a save

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#271]
some user's are getting duplicate hours due to clicking save, and then save & close before the first save returns.  disabling the buttons during the save should fix this.

hub thread: https://powerofus.force.com/0D58000003EU7S1

**Comment by mpusto** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005QCqVAAW" target="_blank">W-018124</a>
