### ISSUE TITLE
 Some Sites pages don't refresh after save when using Firefox, IE, Edge Browsers

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#273]
the PersonalSitesReportHours page does submit hours, but the page does not refresh to display the confirmation message.  I can reproduce on Mac Firefox.  Works fine on Mac Chrome.  User reported this problem against Windows Firefox.  Says it works fine on Windows Internet Explorer. 

Hub thread: https://powerofus.force.com/0D58000003GzdC7

**Comment by davidhabib** [comment]
**lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005KmaQAAS" target="_blank">W-018006</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.95 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.95
