### ISSUE TITLE
latest security scan shows fls/crud checks needed

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#274]
version 3.93 of the package ran thru the Force.com Source Scanner shows issues with missing FLS and CRUD checks.  These were not flagged in the initial security review back in 2011.

[c_stagingreport_sfmcxwp5_24049.html.zip](https://github.com/SalesforceFoundation/Volunteers-for-Salesforce/files/845551/c_stagingreport_sfmcxwp5_24049.html.zip)

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005QClVAAW" target="_blank">W-018088</a>

**Comment by judisohn** [comment]
@davidhabib @joy-sfdo Now that V4S has passed security review, can this be closed?
