### ISSUE TITLE
Customize fields on Job Recurrence Schedule

### ISSUE THREAD

**Issue by brianpickett** [SalesforceFoundation/Volunteers-for-Salesforce#281]
For some clients it makes sense to add custom fields to the Volunteer Shift record. This enhancement request is for the Job Recurrence Schedule to allow for these custom fields to be added to the wizard so they are populated along with the other shift details.

**Comment by mpusto** [comment]
@brianpickett Can you add this as an Idea in the HUB? We have a category for Volunteers and it will get more visibility, votes, and discussion in the HUB.
