### ISSUE TITLE
PersonalSiteContactInfo hits system exception on Show More

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#283]
hub thread here: https://powerofus.force.com/0D58000003LJojK

due to known issue: https://success.salesforce.com/issues_view?id=a1p30000000T0tvAAC

orgs are sometimes hitting the following problem when they click on the Show More link under the Upcoming Volunteer Hours related list on the PersonalSiteContactInfo page.  The get a unauthenticated error, since the user is currently the Sites Guest User and Sites won't display the system error.  If you are logged in and use the PersonalSiteContactInfo page, you will see that the system exception is:

No such column 'lastvieweddate' on entity 'GW_Volunteers__Volunteer_Hours__c'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names. 

Here is debug log:
[V4SPersonalSiteContactInfoDebugLog.txt](https://github.com/SalesforceFoundation/Volunteers-for-Salesforce/files/984899/V4SPersonalSiteContactInfoDebugLog.txt)

This is due to the GUS issue W-2330031 which keeps getting put back on the backlog, so no fix any time soon.  It happens in V4S since one of our shared classes needs to stay at api 25, and the workaround is to make all classes > api 28.  Unfortunately V4S cannot do that at this time.  Not sure how we can work around this.  Maybe by explicitly removing LastViewedDate from our soql?

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006JPEyAAO" target="_blank">W-018587</a>

**Comment by judisohn** [comment]
@davidhabib glad to see you got to the bottom of this as I know it was affecting a few users. What is the downside to removing that field from the soql?

**Comment by davidhabib** [comment]
we don't explicitly add that field to the soql.  we just get all fields returned by the system.  that will be one of the possible solutions to try.

**Comment by slawnikmj** [comment]
Just a quick update here. It appears this is not presenting in our full sandbox which is on Summer '17. Any chance there's a fix in that release?

**Comment by davidhabib** [comment]
Thanks for the update Michael.  I'm not aware that Salesforce core did anything to address this issue.  I was hoping to find a reproducible case in my own DE org, so I could experiment with workarounds.  the known issue hasn't been updated by Salesforce core to say its fixed.

**Comment by slawnikmj** [comment]
Hi @davidhabib et al. I'm not sure what changed, but Show More is working in our production org as well now, and we're not on Summer '17 until June 10.

**Comment by davidhabib** [comment]
great!  weird, but great!

**Comment by judisohn** [comment]
@davidhabib Another customer suddenly reporting this [again](https://powerofus.force.com/0D58000003X4lhm).

**Comment by Szandor72** [comment]
Sorry for hijacking - ive got the same problem in my package. 

has anyone found a workaround for this particular issue? I have tried removing 'lastvieweddate' by editing the query string before the soql being executed to no avail.

**Comment by davidhabib** [comment]
tried again to reproduce in my DE org with unmanaged code, so I can try out work arounds, but unfortunately, I can't get it to happen.  I checked, and Salesforce has not fixed the underlying issue yet, and it doesn't sound like it will be addressed anytime soon.
