### ISSUE TITLE
Field level security error

### ISSUE THREAD

**Issue by chargerbabe** [SalesforceFoundation/Volunteers-for-Salesforce#284]
I have followed instructions on allowing read, edit, view all appropriately. Though my screenshots don't look exactly like th configuration guide when it says to allow view on field level security. Did I miss anything? Also how do i edit sign up page to add upload document (step by step, where do I find the place to even insert the code). Amateur SF admin here. Thanks!

Field GW_Volunteers__Volunteer_Job__c.Description__c needs to have field level security enabled on the Site's Guest User profile. Please see the V4S Installation & Configuration Guide.
Field GW_Volunteers__Volunteer_Job__c.Location_Information__c needs to have field level security enabled on the Site's Guest User profile. Please see the V4S Installation & Configuration Guide.
Field GW_Volunteers__Volunteer_Job__c.Number_of_Shifts__c needs to have field level security enabled on the Site's Guest User profile. Please see the V4S Installation & Configuration Guide.
Field GW_Volunteers__Volunteer_Job__c.Skills_Needed__c needs to have field level security enabled on the Site's Guest User profile. Please see the V4S Installation & Configuration Guide.
Field GW_Volunteers__Volunteer_Job__c.Volunteer_Website_Time_Zone__c needs to have field level security enabled on the Site's Guest User profile. Please see the V4S Installation & Configuration Guide.
Field GW_Volunteers__Volunteer_Job__c.Location_Street__c needs to have field level security enabled on the Site's Guest User profile. Please see the V4S Installation & Configuration Guide.
Field GW_Volunteers__Volunteer_Job__c.First_Shift__c needs to have field level security enabled on the Site's Guest User profile. Please see the V4S Installation & Configuration Guide.
Field GW_Volunteers__Volunteer_Shift__c.Number_of_Volunteers_Still_Needed__c needs to have field level security enabled on the Site's Guest User profile. Please see the V4S Installation & Configuration Guide.
Field GW_Volunteers__Volunteer_Shift__c.Description__c needs to have field level security enabled on the Site's Guest User profile. Please see the V4S Installation & Configuration Guide.
Field GW_Volunteers__Volunteer_Shift__c.System_Note__c needs to have field level security enabled on the Site's Guest User profile. Please see the V4S Installation & Configuration Guide.

**Comment by judisohn** [comment]
Hi @chargerbabe Please post in the [Volunteers for Salesforce group](https://powerofus.force.com/0F980000000Cjjx) in the Power of Us Hub and someone will be able to point you in the right direction. We leave Github issues here only for actionable items, rather than troubleshooting and support. Thanks for understanding!
