### ISSUE TITLE
Uninstall fails because Volunteer Campaign Record Type holds reference to deleted Campaign

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/Volunteers-for-Salesforce#291]
Create an Active Campaign

(Volunteer Campaign Record Type refers to the Campaign record)

Delete the Campaign. 

Attempt to uninstall V4S. 

Uninstall fails because the Record Type is holding a reference to the deleted Campaign record.
![screen shot 2017-07-07 at 12 22 41 pm](https://user-images.githubusercontent.com/204643/27974046-1708b03c-6311-11e7-9a9e-60da5c1b0566.png)

![screen shot 2017-07-07 at 12 22 53 pm](https://user-images.githubusercontent.com/204643/27974052-1f6f5b54-6311-11e7-8e00-cf7ee4b6b604.png)

**Comment by judisohn** [comment]
@chrismcmahon A deleted record is still there in the database as far as the uninstall is concerned. You need to go to the recycle bin and empty it in order to hard delete the record so the uninstall won't see it.
