### ISSUE TITLE
V4S: custom fields that contain "other" or "mailing" don't get copied to new contacts

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#295]
When using the Sites pages, if the Contact has custom fields that contain "other" or "mailing" in their developer name, the V4S code in CreateOrUpdateContactFS() incorrectly assume the field is part of an address compound field, and it doesn't copy the field value to the new contact we are going to create.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007kMAfAAM" target="_blank">W-019999</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.104 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.104
