### ISSUE TITLE
V4S: security errors in Campaign Wizard don't display on page

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#304]
if we run into any security exceptions when cloning a volunteer campaign, or create a sample volunteer campaign, we don't display the page message and incorrectly redirect to the new campaign.  The cause is that we have try/catch blocks in CloneExistingJobsAndShifts() and CreateSampleJobsAndShifts() which should be removed, so that the method Save() knows the errors occurred.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003cEk5AAE" target="_blank">W-020598</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.99 (Beta 2)

**Comment by cpolcyn** [comment]
Included in production release rel/3.99
