### ISSUE TITLE
Job Sign Up pop up does not work with Firefox after version 3.99

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Volunteers-for-Salesforce#313]
[Thread.](https://powerofus.force.com/0D58000003j1ytE)

@davidhabib has replicated the problem in Firefox Mac from VolunteersJobListingFS - likely due to updated jqueryui

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000001SDF8AAO" target="_blank">W-020955</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.100 (Beta 1)

**Comment by cpolcyn** [comment]
Included in production release rel/3.100
