### ISSUE TITLE
V4S: JobCalendar page should display FLS incorrectly set

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#315]
much like VolunteersJobListingFS displays error messages if FLS is not set for the Site's Guest User Profile for any fields being referenced, we should do the same thing on the JobCalendar page, so that it doesn't display as empty with no indication why.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000001SDJUAA4" target="_blank">W-020958</a>

**Comment by cpolcyn** [comment]
Closed by https://github.com/SalesforceFoundation/Volunteers-for-Salesforce/pull/317

**Comment by mrbelvedere** [comment]
Included in beta release 3.101 (Beta 4)

**Comment by cpolcyn** [comment]
Included in production release rel/3.101
