### ISSUE TITLE
VolunteersJobListingFS lists no jobs when VolunteersJobListing does

### ISSUE THREAD

**Issue by wallingd** [SalesforceFoundation/Volunteers-for-Salesforce#316]
After configuration, VolunteersJobListingFS displays no job listings. Have attempted empty FS, minimal fieldset (e.g. Volunteer org. only), and a few fields, ensuring all have permissions.  Repro link: 
http://bbrc.force.com/GW_Volunteers__VolunteersJobListingFS

Corresponding VolunteersJobListing displays full compliment of job listings.  Repro link:
http://bbrc.force.com/GW_Volunteers__VolunteersJobListing

**Comment by judisohn** [comment]
Please post in the [Volunteers for Salesforce group](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000Cjjx) in the Power of Us Hub for further troubleshooting. We use github issues for actionable bugs & issues for developers. Thanks!
