### ISSUE TITLE
V4S VolunteersJobListingFS page Sign Up link for Job (not Shift) broken

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#325]
hub thread: https://powerofus.force.com/0D58000003oEMv3

I believe our recent work to locate the popup relative to the signup link's location is not working correctly when we are just displaying a Job button (ie, no shifts).

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008v6Z6AAI" target="_blank">W-021357</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.103 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.103
