### ISSUE TITLE
Volunteers Help Page on Trial Orgs will have Broken Power Of Us Hub Links

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Volunteers-for-Salesforce#334]
Trialforce intentionally breaks anything that looks like a salesforce ID, including in the Visualfroce page body.
We need to update any link with a SFId like the link on the Volunteers Help Page to link to the named resource page.
Example:
https://powerofus.force.com/kA080000000Cj9S
-- should be --
https://powerofus.force.com/articles/Resource/Volunteers-for-Salesforce

**Comment by jjbennett** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009BCDrAAO" target="_blank">W-021794</a>

**Comment by aordoquiSFDO** [comment]
The links have been updated.  If new links are found that still contain SFid, please reopen this issue with the location of the bad link.
