### ISSUE TITLE
V4S: VolunteersSignupFS page broken if using FileUploadLabel URL parameter

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#336]
hub thread: https://powerofus.force.com/0D58000003vC6IG

user is reporting getting the error: 
apex:inputFile can not be used in conjunction with an action component, apex:commandButton or apex:commandLink that specifies a rerender or oncomplete attribute.

this error is likely due to either a change in what Salesforce supports for file uploading, or in how V4S was handling updates on its page.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009KC7CAAW" target="_blank">W-022138</a>

**Comment by JuliaKhonUna** [comment]
Hello Salesforce, 
is there any update on this bug? Any suggested workarounds? Help is appreciated.

**Comment by jesslopez-sf** [comment]
Duplicate of https://github.com/SalesforceFoundation/Volunteers-for-Salesforce/issues/282
