### ISSUE TITLE
Field for total number of non-Canceled hours on Shift

### ISSUE THREAD

**Issue by notbryant** [SalesforceFoundation/Volunteers-for-Salesforce#338]
Currently GW_Volunteers__Total_Volunteers__c holds the "Total" number of volunteers who have confirmed or completed their hours. (I think that field is poorly named, but backwards compatibility is a thing so it's not what this issue is about.)

Right now it's impossible to set a max count for *registrants* for a shift. There's no way to say "I want to allow 10 people to register ('Web Sign Up') for this shift" aside from creating a flow to automatically set them to confirmed. I don't find this an acceptable solution because (a) it's not true because they have not confirmed and (b) I'm sure there's a crapton of logic elsewhere that hinges on if the status is 'Confirmed' hours.

(Actually, I'd like an explanation for what 'Confirmed' is _supposed_ to mean in this framework.)

The shared code for [VolunteerHoursTrigger](https://github.com/SalesforceFoundation/Volunteers-for-Salesforce/blob/master/src/classes/VOL_SharedCode.cls#L644) already does the heavy lifting so adding a new field based on "NOT LIKE '%Canceled%'" would be fantastic.

Create a new field, create a new ```map<Id, Double>```, and boom, now we can determine how many people are actually registered.

**Comment by judisohn** [comment]
Hi @notbryant Do me a favor and post this as an Idea for Volunteers in our Idea board [here](https://powerofus.force.com/hub-ideas?product=Volunteers%20for%20Salesforce). 

That's the best place for our product managers and community to see and consider. Thanks!
