### ISSUE TITLE
Creating new campaign using Volunteer Wizard is not working

### ISSUE THREAD

**Issue by saimarella** [SalesforceFoundation/Volunteers-for-Salesforce#340]
Hi

I am trying to create a new campaign using volunteer wizard by cloning an existing campaign to get the jobs/shifts etc.

This fails with an error when I click on Save.

_Error: You don't have the permissions required to view GW_Volunteers__Volunteer_Job__c.gw_volunteers__external_signup_url__c. Please contact the system administrator._

I have administrator privileges. Moreover, I have done this for several campaigns in the past. Not sure what has changed.

If I click on Save again (despite the error), I get a different error
_Error: cannot specify Id in an insert call_

Can someone help me on this issue?

Thanks,
Sai.

**Comment by davidhabib** [comment]
you need to enable field level security on all of the fields on the Job, Hour, and Shift objects.  this has been posted extensively in the Hub.  Please use the hub for asking these type of questions.  https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000Cjjx
we only enter issues into gitHub after the team has confirmed it is an issue.
