### ISSUE TITLE
V4S: Personal Site doesn't correctly show upcoming shifts

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#345]
If the PersonalSite is viewed on the day of the shifts, depending on which time zone those shifts are for, they may not be displayed.

hub thread: https://powerofus.force.com/0D58000003z3Ofp

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009lp2FAAQ" target="_blank">W-022903</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.105 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.105
