### ISSUE TITLE
Cannot clone PersonalSiteJobCalendar page

### ISSUE THREAD

**Issue by britishboyindc** [SalesforceFoundation/Volunteers-for-Salesforce#347]
Trying to add some custom text to Job Calendar page, so wanted to clone the V4SF page, use existing page include, and then just customize the site template to use my own page with the new custom text

That approach works fine for other pages, but when I clone Job Calendar and click save, I get this error:
ERROR deploying ApexPage pages/NP_PersonalSiteJobCalendar.page: Invalid tabStyle 'Shift_Calendar__tab' specified.

I assume because I am referencing the GW_Volunteers__JobCalendar page from outside the namespace, the  tab style needs to include the namespace on the packaged page? Which makes no sense to me, since I am just including the page, but wouldn't be the first time namespace references have behaved...strangely.

**Comment by britishboyindc** [comment]
I was able to get round it by creating a local version the tab, but not 100% sure if that is going to work when I try package this all up...so I think ideally we'd change the namespace for that reference in V4SF to use an explicit namespace

**Comment by davidhabib** [comment]
unfortunately, with an explicit namespace, then we aren't able to do development and testing in non-namespaced orgs.
