### ISSUE TITLE
V4S CSS Issue - Sign up button inconsistency

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/Volunteers-for-Salesforce#350]
In both the VolunteersJobListing and VolunteersJobFS Visualforce pages, we display sign up buttons differently depending on whether the Volunteer Job has shifts or not. If a developer would like to customize the CSS for the Job Listings page(s) and have the sign up links/buttons have a consistent style, it isn't currently possible. The buttons have a class that can be overridden (cssJobShiftSignup), but the links do not have any Id or CSS styles/classes to override. 

This Issue is being filed to ask for a consistent input element for the Sign Up functionality, as well as a consistent class to override with CSS.

![job listings](https://user-images.githubusercontent.com/37851761/42831105-54dec3c0-89a2-11e8-8320-33eb4d40b93d.jpg)

If the Volunteer Job has associated shifts, we display a dataTable with listings for each Shift, along with a link to sign up:

VolunteersJobListing: Lines 106-110

```
<a href="SignUp" onclick="
                        var x = JobShiftDateTimeString('{!shift.Start_Date_Time__c}', '{!shift.Duration__c}');            
                        OpenSignUpDlg('{!job.Id}', '{!shift.Id}', '{!JSENCODE(job.Name)}', x); 
                        return false;"
                        >sign up</a>
```

VolunteersJobListingFS: Lines 198-203

```
<a  id="{!shift.Id}"  href="SignUp" onclick="
                        var x = '{!JSENCODE(shift.System_Note__c)}';   
                        if (x == '') x = JobShiftDateTimeString('{!shift.Start_Date_Time__c}', '{!shift.Duration__c}');
                        OpenSignUpDlg('{!job.Id}', '{!shift.Id}', '{!JSENCODE(job.Name)}', x);
                        return false;"
                        >{!$Label.labelLinkSignUp}</a>
```

If, on the other hand,  the Volunteer Job has no associated shifts, we display a submit button:

VolunteersJobListing: Line 101
`<input type="button" value="Sign Up" class="cssJobShiftSignup" onclick="OpenSignUpDlg('{!job.Id}', '', '{!JSENCODE(job.Name)}', ''); return false;"/>`

VolunteersJobListingFS: Line 175
`<input type="button" id="{!job.Id}" value="{!$Label.labelButtonSignUp}" class="cssJobShiftSignup btn" onclick="OpenSignUpDlg('{!job.Id}', null, '{!JSENCODE(job.Name)}', ''); return false;"/>:`

@jesslopez-sf

**Comment by coriobriensfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYByhAAH" target="_blank">W-026349</a>
