### ISSUE TITLE
Full_Name__c Can't Be Sorted in Query Call (Shield)

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Volunteers-for-Salesforce#352]
An org with Deterministic Encryption enabled is getting the following error when clicking on the Mass Edit Volunteer Hours button:

`field 'Full_Name__c' can not be sorted in a query call`

Full_Name__c is a formula field on the Volunteer Hours object that concatenates Contact First Name and Contact Last Name. Contact Name is not currently encrypted in this org, yet the only way I'm able to replicate the error is if I encrypt the Contact Name field (Salesforce Support has decrypted the field manually twice).

Running a Describe on the field shows that it is not sortable in this org.
`System.Debug(gw_volunteers__volunteer_hours__c.gw_volunteers__full_name__c.getDescribe().isSortable());`

Running a Describe on Contact First Name and Contact Last Name show they are sortable, so this Issue/Work Item is a request to focus just on changing the sorting of this query for now:

[VOL_CTRL_VolunteersBulkEnterHours, Line 211](https://github.com/SalesforceFoundation/Volunteers-for-Salesforce/blob/master/src/classes/VOL_CTRL_VolunteersBulkEnterHours.cls#L211)

**Steps to Repeat:**
1. In an org with Shield Platform Encryption enabled (I can provide further instructions on setting this up), make sure that Contact Name is encrypted.
2. Go to a Volunteer Job page
3. On the Volunteer Hours related list, click the button called "Mass Edit Volunteer Hours"
Error displayed: "field 'Full_Name__c' can not be sorted in a query call" .

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYCjPAAX" target="_blank">W-026904</a>

**Comment by jesslopez-sf** [comment]
Workaround:

- Go to Setup -->Encryption Policy.
- Click the Encrypt Fields link
- Click the Edit button
- Click the checkbox next to Contact Name and then select Deterministic as the Encryption Scheme
- Click Save. It may take a few minutes, but the administrator will receive an email when finished.
- Then hit Edit again and uncheck the box next to Contact Name.
- Click Save. It may take a few minutes, but the administrator will receive an email when finished.


For whatever reason, turning encryption back on for this field and turning it off made our formula field sortable again and the Visualforce error went away.
