### ISSUE TITLE
Signing up for single shift generates volunteer thank you with right date but wrong shift time

### ISSUE THREAD

**Issue by TeoPopa** [SalesforceFoundation/Volunteers-for-Salesforce#354]
I'm not sure where to post this but landed on this issues page when searching for volunteers for salesforce help.

We are installing V4S now in our production environment and testing signups.

Most of our shifts reoccur weekly for a 2-3 month period of time, coinciding with our programming schedule. When a new volunteer signs up for a shift, they get a confirmation "Thank You" email (Volunteer Job Signup Thank You Email Template). In this template, the field {!GW_Volunteers__Volunteer_Hours__c.GW_Volunteers__Shift_Start_Date_Time__c} gives the right date on the upcoming shift, but the time wrong and is plus 6 hours. Our shift is for 9/5/2018 3:45 PM, the email template sends 9/5/2018 9:45 PM.

If we sign the volunteer up with a Volunteer Recurrence Schedule for the next 3 shifts in this series, the confirmation "Thank You" emails for those additional 3 shifts send through with the correct time. The merge field in the template is the same merge field as when they signed up for a single shift.

![image](https://user-images.githubusercontent.com/42358801/44058858-c737be98-9f0c-11e8-8b92-a05109366ed5.png)

![image](https://user-images.githubusercontent.com/42358801/44058875-d36ae226-9f0c-11e8-95b1-6cd83647abb5.png)

**Comment by coriobriensfdo** [comment]
@TeoPopa We actually have a group in the Power of Us Hub for any issues and assistance with the package: https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000Cjjx Can you log into the Hub and post there instead?

Also, take a look at the Setup Guide or the Trailhead around the Time Zone fields. There is a TimeZone field on a few different objects that control which time is posted and any one of them could be causing the issue. 

https://powerofus.force.com/articles/Resource/Volunteers-for-Salesforce-Setup-and-Configuration-Guide
