### ISSUE TITLE
XSS is triggered in HTML email template preview

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Volunteers-for-Salesforce#360]
Stored XSS in a custom email template allows code execution when displayed on the "Send Bulk Email" page.

**Comment by jjbennett** [comment]
lurch: attach W-024083

**Comment by mrbelvedere** [comment]
Included in beta release 3.106 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release 3.106
