### ISSUE TITLE
Managed package installation by non-English user fails

### ISSUE THREAD

**Issue by davisagli** [SalesforceFoundation/Volunteers-for-Salesforce#364]
Installation by a user whose language is set to something other than English hits a platform error.

Steps to reproduce:
1. Create a fresh scratch org without V4S installed
2. In Setup > My Personal Information > Language & Time Zone, change your user's language to English.
3. Install Volunteers for Salesforce via the install link or using "cci flow run install_prod"

This results in an error like this: Fallo de instalación, Details: La instalación solicitada ha fallado. Inténtelo de nuevo.  Ninguno de los datos ni la información de configuración de su organización de Salesforce debe verse afectado por este error.  Si el error persiste, póngase en contacto con el Servicio de soporte de salesforce.com mediante los canales habituales y el número de referencia. 556361905-20102 (687958943)

Translation: Installation failure, Details: The requested installation has failed. Try again. None of the data or configuration information in your Salesforce organization should be affected by this error. If the error persists, contact Salesforce.com Support via the usual channels and the reference number.

**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fOFfAAM" target="_blank">W-028791</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.109 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release 3.109
