### ISSUE TITLE
Enhancement Request: Add reCaptcha capabilities in public facing visualforce pages

### ISSUE THREAD

**Issue by badkeith** [SalesforceFoundation/Volunteers-for-Salesforce#365]
Would be great to be able to enable reCaptcha in the public facing forms to enable some spam protection.

**Comment by coriobriensfdo** [comment]
@badkeith Thanks for taking the time to make this suggestion! I'll actually need to close it though as we don't log proposed requests here on GitHub and instead use the Idea tab in the Power of Us Hub. Can you create an idea for that there?
https://powerofus.force.com/hub-ideas?product=Volunteers%20for%20Salesforce
