### ISSUE TITLE
VRS does not generate hours in past

### ISSUE THREAD

**Issue by jspeedy** [SalesforceFoundation/Volunteers-for-Salesforce#371]
VRS created/edited do not create new volunteer hours for any shifts before the current date.  The documentation in [https://powerofus.force.com/articles/Resource/V4S-Recurrence-Schedule-Processing](url) states VRS should create Volunteer Hours in past and future.

_When a VRS is modified, the system:

Evaluates all existing Volunteer Hours attached to the VRS.
Creates Volunteer Hours if there are no existing matching Volunteer Hours (includes past and future Hours)._

This can be recreated by creating a new JRS and VRS with dates in the past.  Volunteer Hours for dates prior to creation date will not be created.

**Comment by judisohn** [comment]
Hi @jspeedy We don't provide direct support here on Github - your best bet is to post this in the [Volunteers for Salesforce group](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000Cjjx) in the Power of Us Hub and someone can help troubleshoot what's going on in your org. Thanks!

**Comment by jspeedy** [comment]
@judisohn Thanks!  I moved this over to the Hub.  As a note, I have reviewed the code in my attempts to troubleshoot or find a workaround and I think this functionality is not currently included (I hope I'm wrong!).  I would be open to submitting a pull request if you are accepting them from the community and would implement a fix faster :)
