### ISSUE TITLE
Personal Site Contact Labels XSS Vulnerability

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Volunteers-for-Salesforce#373]
In order to ensure no XSS Vulnerabilities exist, encode all Labels used in JQuery.

**Comment by jjbennett** [comment]
**lurch: attach W-026536

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYCDsAAP" target="_blank">W-026536</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.108 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release 3.108
