### ISSUE TITLE
When a second VRS is created for the same contact on the same day, all hours from first VRS are reparented to second

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/Volunteers-for-Salesforce#377]
[Reported Hub Post](https://powerofus.force.com/0D51E00004gHTsj)

**Issue:** When assigning Job Recurrence Schedule (JRS) for different shifts (9am & 11am) on the same day (not overlapping) to the same Contact via two new Volunteer Recurrence Schedule (VRS), all Volunteer Hours records are being reparented from the first JRS to the second. This also incorrectly sets the "Planned Start Date & Time" field value from 9am to 11am.

**Expected Result:** All 9am Volunteer Hours records relate to the 9am VRS, and the 11am Volunteer Hours records relate to the 11am VRS.

**Customer Use Case:** A Contact will be part of two different Volunteer Shifts that are happening on the same day for the duration of a school year. The Contact is volunteering at 9am and then again at 11am every Monday for a year. 

**Steps to Recreate:**
1. Create a Volunteer Job. 
2. Create two new Job Recurrence Schedules, one for 9am and one for 11am, recurring each Monday. Make the duration for each one only 1 hour. All other fields can be the same (irrelevant for the test).
3. On the Volunteer Job, create a new Volunteer Recurrence Schedule for the 9am JRS for a Contact in the org. Open the new VRS 9am record in a new tab, and note all the Volunteer Hours records have been created for 9am.
4. On the Volunteer Job, create a second Volunteer Recurrence Schedule for the 11am JRS for the same Contact you used for the 9am one. Open the new VRS 11am record in a new tab.
5. Go back to the VRS 9am record, and note that there are no Volunteer Hours.
6. Go back to the VRS 11am record, and note that it now contains both the 9am and 11am Volunteer Hours records. 
7. Open one of the 9am Volunteer Hours records, and note that the "Planned Start Date & Time" field indicates 11am instead of 9am. Also note the values in the related "Volunteer Recurrence Schedule" field and "System Note" field doesn't match.
 
**See images:**
<img width="410" alt="screen shot 2019-01-15 at 12 54 09 pm" src="https://user-images.githubusercontent.com/37851761/51209240-aad12280-18c4-11e9-9618-4aac02fad8a9.png">

<img width="927" alt="screen shot 2019-01-15 at 12 55 46 pm" src="https://user-images.githubusercontent.com/37851761/51209417-07344200-18c5-11e9-8417-2c9219e51667.png">
<img width="936" alt="screen shot 2019-01-15 at 12 56 31 pm" src="https://user-images.githubusercontent.com/37851761/51209418-07ccd880-18c5-11e9-9073-c174452f000a.png">

**Comment by coriobriensfdo** [comment]
**Lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQniQAE" target="_blank">W-030767</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.113 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release 3.113
