### ISSUE TITLE
Space being interpreted as Text in Shift Calendar &nbsp;&nbsp

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/Volunteers-for-Salesforce#379]
[Thread](https://powerofus.force.com/0D51E00004gIo6e)
[Another Thread](https://powerofus.force.com/0D51E00004gIvF0)
[Another Thread](https://powerofus.force.com/0D51E00004gIz8d)

Issue:

When viewing the V4S Shift Calendar in the Day or Week view, additional fields are included # confirmed and # available shifts. After the "Confirmed" number, the text `&nbsp;&nbsp` is added.

<img width="988" alt="screen shot 2019-01-30 at 9 56 26 am" src="https://user-images.githubusercontent.com/37851761/52002972-1ba53c80-2478-11e9-9e75-4e511896a66e.png">

Steps to Reproduce:
1. Click on Shift Calendar tab in org with V4S installed. 
2. Change view to Day or Week view. 

**Workaround until this is fixed:** 

1. Navigate to setup -> custom labels
2. Locate "labelShiftNumbers"
3. In the "Local Translations / Overrides" section, click "New Local Translation / Overrides"
4. Select English as the Language, and enter "confirmed: {0} - available: {1}" (without the quotes) in the Translation Text box.

**Comment by coriobriensfdo** [comment]
**lurch: add

**Comment by jjbennett** [comment]
Fixed in #382
