### ISSUE TITLE
New workflow rule for emailing web signup with shift information

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#39]
Volunteers currently has a workflow rule on Contacts and Leads to thank the person for signing up, but it does not include the shift information.  While user's can create their own rule to accomplish this, it would be nice to include.  Here is what Earthcorps rule is:

Object: Volunteer Hours
Evaluation Criteria: Only when a record is created
Rule Criteria: (Contact: Email not equal to null) and (Volunteer Hours: Created By equals Volunteers Site Guest User) 

Their rule then does three workflow actions:

Type                         Description 
Email Alert              Volunteer Signup Notification Email Alert 
Email Alert              Notify Volunteer Manager of New Volunteer Sign Up 
Field Update           Update Status to Confirmed

**Comment by JackMurphyJr** [comment]
I am trying to get shift details on an workflow email, it doesn't seem to work. Any tips for this? Job shows just fine but not the shift details

**Comment by davidhabib** [comment]
please post questions like these on the Salesforce Foundation's Power of Us Hub, in the Volunteers for Salesforce App group at https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000Cjjx

The Hub is an online community of users and consultants who help each other with questions.  I also monitor the group and will chime in if needed.
