### ISSUE TITLE
Links to visualforce pages do not work in a dev scratch org.

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Volunteers-for-Salesforce#395]
When creating a scratch org without the namespace, GW_Volunteers, links to the various visualforce pages do not work since they are hard coded with the namespace.

**Comment by jjbennett** [comment]
**lurch: attach W-031515

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008Ll7WQAS" target="_blank">W-031515</a>

**Comment by katherinemitchell** [comment]
I read the issue title, and I don't have any edits. Thanks, @jjbennett.

**Comment by mrbelvedere** [comment]
Included in beta release 3.110 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release 3.110
