### ISSUE TITLE
PersonalSiteContactInfo is not being styled correctly.

### ISSUE THREAD

**Issue by Syllinger** [SalesforceFoundation/Volunteers-for-Salesforce#397]
It looks like this page is supposed to be loading Bootstrap, but when trying to access it from a fresh org, and following the configuration steps on Trailhead, the page appears unstyled regardless of whether I navigate directly to it, or from the PersonalSiteTemplate page.

Looking at the source, I noted that there are no `Load jQuery` or `Load Bootstrap` sections.

**Comment by Syllinger** [comment]
It looks like this page is supposed to be loading Bootstrap, but when trying to access it from a fresh org, and following the configuration steps on Trailhead, the page appears unstyled regardless of whether I navigate directly to it, or from the PersonalSiteTemplate page.

**Comment by coriobriensfdo** [comment]
@Syllinger We actually don't have product support here in GitHub, and I don't believe this is a bug in the code as we load Bootstrap in the PersonalSiteTemplate page, not in the individual pages themselves. 

Instead, can you please post your issue in the [Volunteers For Salesforce](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000Cjjx) group in the Hub and I can share further details on how to fix that.

**Comment by Syllinger** [comment]
@coriobriensfdo I mentioned that in the body of my issue submission. When navigating from the PersonalSiteTemplate page, the link forwards the user to to respective page, but doesn't retain the assets. It looks like the template routing is not working as expected.

**Comment by coriobriensfdo** [comment]
@Syllinger If there is an actual bug, then we need to be able to repro it in an independent org. If you don't mind taking just a few mins and posting in the V4S group linked above I can help you there, and either re-open this Issue or create a new one should there be something that we need to fix in the package.
