### ISSUE TITLE
Authentication issue with PersonalSite Template and error

### ISSUE THREAD

**Issue by AkankshaGa** [SalesforceFoundation/Volunteers-for-Salesforce#417]
I am trying to setup PersonalSite Template under Volunteer for Salesforce package in Sandbox. Everything is done but on clicking the email link and previewing it as admin, I am getting error- 'duplicate field selected: FirstName' and page is showing Authorization required.
I have not modified anything related to this field. Is there an issue in the managed package?
I have removed all the links to four navigation pages under template to narrow down the issue in a VF page copy. But it is still showing me this error. It looks something is wrong with the template itself and not the navigational pages.
Any help is appreciated.
Thanks

**Comment by judisohn** [comment]
Hi @AkankshaGa We don't provide customer support on Github. Please post in the Power of Us Hub and [include the Volunteers for Salesforce topic](https://powerofus.force.com/s/topic/0TO8000000001SLGAY/volunteers-for-salesforce-v4s), and someone will be able to help you troubleshoot your issue there.
