### ISSUE TITLE
Broken Links on GW_Volunteers__PersonalSiteContactInfo page

### ISSUE THREAD

**Issue by kschaefges** [SalesforceFoundation/Volunteers-for-Salesforce#438]
### **Use Case**
When a client's volunteer logs into their PersonalSitesPage, there is a link on the Scheduled Volunteer Shift section to view the details of their upcoming shifts.  There can also be a link on the section "Your Recent Volunteer History" to link to the Volunteer Shift, if the Field Set has been edited to include the Volunteer Shift on the Volunteer Hours object.

When either of those links are clicked by a volunteer, they are getting routed to PageNotFound errors, rather than the page that will display the volunteer shift details.

### **Description**
The VF page: GW_Volunteers__PersonalSiteContactInfo includes code to redirect the volunteer user to the PersonalSiteJobListing (GW_Volunteers__PersonalSiteJobListing) page with shift specific parameters on [line 152](https://github.com/SalesforceFoundation/Volunteers-for-Salesforce/blob/master/src/pages/PersonalSiteContactInfo.page#L152).  The code is referencing the custom setting; packagesettings__c. It seems as though the packagesettings__c.namespaceprefix is not being populated in the URL build in line 152.

### **Steps to Replicate**
1. In a V4S org, create a volunteer campaign, job. 
2. For that job, create one shift in the past and one in the future.
3. Create a new contact
4. Add that new contact to each of the newly created shifts.
5. For the shift in the past, change the volunteer hours record status to Completed.
6. For the shift in the future, set the volunteer hours record status to Confirmed.
7. Ensure/Create the Volunteers Site and follow any config steps to get the site up and running.
8. Update the Volunteer Hours field set PersonalSiteContactInfoHistory to include the Volunteer Shift
8. Copy the contactID of the contact you've assigned to these shifts
9. Navigate to the <yoursiteurl>/GW_Volunteers__PersonalSiteContactInfo?contactid=<contactid>
10. Click on the detail button next to your upcoming shift - you should be rerouted to the PageNotFound page
11. Click on the link for the shift in the Your Recent Volunteer History - you should be rerouted to the PageNotFound page.

**Comment by kschaefges** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C95qQAC" target="_blank">W-035159</a>

**Comment by gtwright** [comment]
We're having the exact same issue.

**Comment by jesslopez-sf** [comment]
Split the original issue into two. Here's the second one:
#470
