### ISSUE TITLE
V4S Calendar Link not opening Shift in new tab when used in a Community

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/Volunteers-for-Salesforce#442]
See [Hub Thread](https://powerofus.force.com/s/question/0D51E00004ywellSAA/link-to-v4s-calendar-from-a-sf-community)

**Issue:**
When adding a V4S calendar link in a Community the calendar should open in a new tab.

However, when clicking on a shift in the calendar, the url of the shift points back to the community itself rather than the V4S site. 

**Apparent Cause:**
It seems the code behind the V4S calendar is using the deprecated "getCurrentSiteURL" method (was deprecated in API 30) instead of the newer "getBaseUrl" method. "getCurrentSiteURL" was known to "return the referring page's URL instead of the current request's URL". 
https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_sites.htm#apex_System_Site_getCurrentSiteUrl

![Screen Shot 2019-08-14 at 7 41 06 AM](https://user-images.githubusercontent.com/37851761/63030407-1aad8880-be67-11e9-90b7-09fdde320091.png)

**Comment by coriobriensfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C9RtQAK" target="_blank">W-035325</a>
