### ISSUE TITLE
Custom Labels are protected - cannot be referenced

### ISSUE THREAD

**Issue by dschach** [SalesforceFoundation/Volunteers-for-Salesforce#450]
If I want to write a custom Visualforce page that still uses the packaged controller (say, the shifts page) so I can style it better and include some other things, I cannot reference the labels included in the package because they are protected.
Please unprotect them. I don't think it's a concern that they might need to be deleted one day.

**Comment by coriobriensfdo** [comment]
@dschach We don't actually log new feature requests/changes here in GitHub, so I'll need to close this. But, we do log them in the Hub, in the [Ideas area](https://powerofus.force.com/s/ideas?product=Volunteers%20for%20Salesforce). When a new Idea is created it's routed right over to the Product Manager for the product (V4S) in this case, and others in the community can vote on it for future consideration. 

Appreciate your understanding, but let me know if you have any questions.
