### ISSUE TITLE
Custom setting with namespace prefix cannot be referenced

### ISSUE THREAD

**Issue by dschach** [SalesforceFoundation/Volunteers-for-Salesforce#451]
If I want to clone the Visualforce pages in the package and still use the packaged controller, I cannot reference the custom setting with the namespace prefix because it's hidden. It should either be visible and available for use or not used in the package, since end-user customization of the package is important, and forcing hard-coding of the prefix seems like it should be unnecessary.

**Comment by coriobriensfdo** [comment]
@dschach We don't actually log new feature requests/changes here in GitHub, so I'll need to close this. But, we do log them in the Hub, in the [Ideas area](https://powerofus.force.com/s/ideas?product=Volunteers+for+Salesforce). When a new Idea is created it's routed right over to the Product Manager for the product (V4S) in this case, and others in the community can vote on it for future consideration.

Appreciate your understanding, but let me know if you have any questions.
