### ISSUE TITLE
"Still Needed: #" custom label no longer showing up in the Shift picklist within Find Volunteers page

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/Volunteers-for-Salesforce#482]
[Hub Post](https://powerofus.force.com/s/question/0D51E00005EzVYzSAN/still-needed-has-disappeared-from-volunteer-shift-picklist-in-find-volunteers-after-upgrade-to-3117)

**Issue:** 
When selecting a Shift record to assign to a Volunteer using the Find Volunteer Visualforce page, before V4S version 3.117 the value from "# Volunteers still needed" was appended to the shift picklist field. After the release, that custom label disappeared. 

Before:
![Screen Shot 2020-02-26 at 11 39 48 AM](https://user-images.githubusercontent.com/37851761/75464925-c5d1eb00-593c-11ea-8a19-7ed30e365ccb.png)

After:
![ovOpUKE](https://user-images.githubusercontent.com/37851761/75465052-f44fc600-593c-11ea-9a9a-4a52ee3eecf7.png)

**Cause:**
Missing parenthesis from a nested ternary statement that is supposed to bring the value from the "# Volunteers still needed" field if the user has access to the Start Date field of the Shift.

**Comment by jjbennett** [comment]
**lurch: attach W-039835

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HsynQAC" target="_blank">W-039835</a>
