### ISSUE TITLE
Visualforce Pages "Does Not Exist"

### ISSUE THREAD

**Issue by seanrmsy** [SalesforceFoundation/Volunteers-for-Salesforce#483]
I am getting the following errors for "SendBulkEmail" , "VolunteersFind", etc. I've checked all the Permission Sets and all seems good. We are viewing in Lightning. Appreciate the advice on where to look next. Thanks.

**Comment by jamesbsfdc** [comment]
Hi Sean, can you log a support case for this? There is a current known issue and we can relate the case to it. Thanks. James

**Comment by seanrmsy** [comment]
Sure. Are you wanting me to post it here: https://help.salesforce.com/?

**Comment by jamesbsfdc** [comment]
Yes please. Here are some directions on things to include in the case: https://powerofus.force.com/s/article/SFDO-CS-Create-a-Tech-Support-Case

And would you mind posting the case number here when done so we can route it to the correct team?

**Comment by seanrmsy** [comment]
25804044

**Comment by coriobriensfdo** [comment]
@seanrmsy because we don't provide support here and we'll be able to help you via your case, I'm going to close this Issue. Feel free to review/post in the Power of Us Hub if you'd like as well, as we have a [Volunteers Group](https://powerofus.force.com/s/group/0F980000000CjjxCAC/volunteers-for-salesforce-app) there.

**Comment by coriobriensfdo** [comment]
@seanrmsy FYI Salesforce has sent out a patch update to fix the issue that was affecting the Mass Email Volunteers, Volunteer Roster, and Find Volunteers buttons on the Job and Shift records in Lightning when the Sharing Settings Site Guest user update was enabled. Can you please ask your users to test and let me know if the issue has been resolved in your org? Thank you so much for your patience as this was researched and resolved.

**Comment by seanrmsy** [comment]
Yes, we checked and can confirm that it appears to be resolved with the update. Thanks!
