### ISSUE TITLE
Volunteers Portal

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#70]
How likely would you use a new feature that allows people to login (with username and password) to view their contact information, volunteer history, and upcoming job shifts? This feature would require the purchase of Customer Portal licenses from the Salesforce Foundation.

Very likely to use  30.19%  
Might use   30.19%  
Would stick with the current no-login we... 21.70%  
Don't plan on having website integration    13.21%  
Not Answered    4.71%

**Comment by RobLofaro** [comment]
Is it possible to use the Volunteers Personal Site features within a Customer Portal?  Portal users do not have access to Campaigns, which seems to be a problem.

**Comment by davidhabib** [comment]
If they hit the Personal Site will logged in with the customer portal license, it won't work.  If the hit the Personal Site with the Sites Guest User and are not logged in, then it should work.

**Comment by RobLofaro** [comment]
Ok, but we don't want them to have to go to two different places.  They
will already be logged into the Portal for other purposes.  Is it possible
to add Personal Site to the portal or do we need to take a different
approach?​

**Comment by davidhabib** [comment]
I have no solution for you.  If the user is logged into a portal license they cannot see campaigns, and thus cannot see V4S objects.  there is nothing I can do about this.  please vote up this idea: https://success.salesforce.com/ideaView?id=08730000000Lge9AAC
