### ISSUE TITLE
Mass Email to Campaign Members

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#73]
Support Mass Email Volunteers to everyone on a campaign, without requiring them to have been assigned to a job or shift.  The current wizard requires Volunteer Hours records.

**Comment by mpusto** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004DBK9AAO" target="_blank">W-016901</a>

**Comment by aordoquiSFDO** [comment]
The send List Email feature has been added to general Salesforce functionality for contacts, campaign members, and leads. To learn more about this feature and how to enable it, [click here](https://help.salesforce.com/articleView?id=email_list_email.htm&type=5). 

If you have any additional questions or comments, please post to the [Volunteers for Salesforce app group in the Hub](https://powerofus.force.com/s/group/0F980000000CjjxCAC/volunteers-for-salesforce-app).
