### ISSUE TITLE
Support qualifications checking on Job Signup

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#90]
Since many organizations have various rules about who is qualified to sign up for a given job, it would be great if Volunteers could support this in a general way.  

Idea: 
- each Job has an optional Contact Boolean Field to test
- the admin can use formula fields or checkbox fields to define their qualifications
- after the contact lookup, we test their qualifcation field, and give an error if the contact field is false.
- would need to have some way for the org to specify what message they want given to the person signing up, so it isn't cryptic.

**Comment by mpusto** [comment]
I'm hesitant to lurch this if there is a simple way to configure using validation rules. Thoughts?

**Comment by davidhabib** [comment]
agreed.  let them use a validation rule.
